-- 2. Next we have two sets: the first set is lines of code and the other is
-- a set of results. Read the code and figure out which results came
-- from which lines of code. Be sure to test them in the REPL.
-- a) concat [[1 * 6], [2 * 6], [3 * 6]]
-- b) "rain" ++ drop 2 "elbow"
-- c) 10 * head [1, 2, 3]
-- d) (take 3 "Julie") ++ (tail "yes")
-- e) concat [tail [1, 2, 3],
--      tail [4, 5, 6],
--      tail [7, 8, 9]]
-- Can you match each of the previous expressions to one of these
-- results presented in a scrambled order?
-- a) "Jules"
-- b) [2,3,5,6,8,9]
-- c) "rainbow"
-- d) [6,12,18]
-- e) 10

-- Solution:
-- a) - d)
-- b) - c)
-- c) - e)
-- d) - a)
-- e) - b)