-- 2. What are the results of the following expressions?
-- a) length [1, 2, 3, 4, 5]
-- b) length [(1, 2), (2, 3), (3, 4)]
-- c) length allAwesome
-- d) length (concat allAwesome)

-- Solutions:
-- a) 5
-- b) 3
-- c) 2
-- d) 5