-- 1. For the following lines of code, read the syntax carefully and
-- decide if they are written correctly. Test them in your REPL after
-- you’ve decided to check your work. Correct as many as you can.
-- a) concat [[1, 2, 3], [4, 5, 6]]
-- b) ++ [1, 2, 3] [4, 5, 6]
-- c) (++) "hello" " world"
-- d) ["hello" ++ " world]
-- e) 4 !! "hello"
-- f ) (!!) "hello" 4
-- g) take "4 lovely"
-- h) take 3 "awesome"

-- Solution:
-- a) Correct
-- b) Wrong. (++) [1, 2, 3] [4, 5, 6]
-- c) Wrong. (++) "hello" " world"
-- d) Wrong. "hello" !! 4
-- e) Correct
-- g) Wrong. take 4 "lovely"
-- h) take 3 "awesome"