-- 3. For the following function
-- func :: [a] -> [a] -> [a]
-- func x y = x ++ y
-- which of the following is true?
-- a) x and y must be of the same type
-- b) x and y must both be lists
-- c) if x is a String then y must be a String
-- d) all of the above

-- Solution
-- d) all of the above