-- Below you’ll find a list of several standard functions we’ve talked about
-- previously. Under that is a list of their type signatures. Match the
-- function to its type signature. Try to do it without peeking at the type
-- signatures (either in the text or in GHCi) and then check your work.
-- You may find it easier to start from the types and work out what you
-- think a function of that type would do.
-- 1. Functions:
-- a) not
-- b) length
-- c) concat
-- d) head
-- e) (<)
-- 2. Type signatures:
-- a) _ :: [a] -> a
-- b) _ :: [[a]] -> [a]
-- c) _ :: Bool -> Bool
-- d) _ :: [a] -> Int
-- e) _ :: Ord a => a -> a -> Bool

-- Solution:
-- a) not :: Bool -> Bool
-- b) length :: [a] -> Int
-- c) concat :: [[a]] -> [a]
-- d) head :: [a] -> a
-- e) (<) :: Ord a => a -> a -> Bool
